name: "Scan Docker Image"
description: "Scan Vulnerability for Docker Image"
inputs:
  image:
    description: "image name"
    required: true
  config:
    description: "config file"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Prepare Scout Arguments"
      shell: bash
      id: arguments
      run: |
        echo "::notice:: Preparing Scout Arguments..."
        source ${{ inputs.config }}
        
        echo "severity=${severity:-critical,high}" >> $GITHUB_OUTPUT
        echo "command=${command:-quickview}" >> $GITHUB_OUTPUT
        if [[ "$ignore_base" == "true" ]]; then
          echo "ignore_base=true" >> $GITHUB_OUTPUT
        else
          echo "ignore_base=false" >> $GITHUB_OUTPUT
        fi
        echo "::notice:: Scout arguments prepared."

    - name: "Scan With Docker Scout"
      uses: docker/scout-action@v1
      with:
        image: ${{ inputs.image }}
        only-severities: ${{ steps.arguments.outputs.severity }}
        command: ${{ steps.arguments.outputs.command }}
        ignore-base: ${{ steps.arguments.outputs.ignore_base }}
