name: "Save Docker Image As Artifact"
description: "Save Built Image as Artifact"
inputs:
  artifact:
    description: "artifact name"
    required: true
  image:
    description: "image name"
    required: true
outputs:
  file:
    description: "Loaded Docker Image Name"
    value: ${{ steps.image-save.outputs.file }}

runs:
  using: "composite"
  steps:
    - name: Save Docker Image
      id: image-save
      shell: bash
      run: |
        file="${{ inputs.image }}.tar"
        docker images
        docker save -o $file ${{ inputs.name }}
        echo "file=$file" >> $GITHUB_OUTPUT   

    - name: Upload Docker Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: ${{ steps.image-save.outputs.file }}
        if-no-files-found: error
