name: "Tag and Push Docker Image"
description: "Tag and Push Docker Image"
inputs:
  namespace:
    description: "docker namespace"
    required: true
  image:
    description: "image name"
    required: true
  tags:
    description: "image tags"
    required: true
  artifact:
    description: "artifact name"
    required: true
  DOCKER_TOKEN:
    description: "docker hub token (push)"
    required: true
  GITHUB_TOKEN:
    description: "github token (tag)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Artifact
      if: ${{ inputs.artifact }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: .image

    - name: Load Docker Image
      if: ${{ inputs.artifact }}
      id: load-image
      shell: bash
      run: |
        # convert inputs.image to filename 
        filename="${{ inputs.image }}"
        filename="${filename//\//-}"
        filename="${filename//./-}"
        filename="${filename//:/-}"
        
        echo "::notice:: Loading Docker Image from ${file}..."               
        image=$(docker load --input ${file} | grep 'Loaded image:' | awk '{print $3}')
        
        echo "::notice:: Docker Image loaded as $image"       
        echo "image=$image" >> $GITHUB_OUTPUT

    - name: Log In To Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.namespace }}
        password: ${{ inputs.DOCKER_TOKEN }}

    - name: Tag And Push Docker Image
      shell: bash
      run: |
        echo "::notice:: Tagging And Pushing Docker Image..."       
        source="${{ inputs.image }}"
        if [ -n "${{ steps.load-image.outputs.image }}" ]; then
          source="${{ steps.load-image.outputs.image }}"
        fi 
        echo "::notice:: > source: $source"
        
        tags="${{ inputs.tags }}"
        for tag in $tags; do        
          target="${{ inputs.namespace }}/$tag"
          echo "::notice:: > tag as: $target"
          
          docker tag $source $target
          echo "::notice:: image tagged"
          
          docker push $target
          echo "::notice:: image pushed"
        done
        
        echo "::notice:: Image tagged and pushed..."

    - name: Authenticate With GitHub
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"             

    - name: Tag Git Commit
      shell: bash
      run: |
        echo "::notice:: Tagging Commit..."     
        tags="${{ inputs.tags }}"
        for tag in $tags; do
          echo "::notice:: > tags: $tags"
        done
        echo "::notice:: Commit tagged..."
