name: "Load Docker Image From Artifact"
description: "Load docker image from a given artifact"
inputs:
  image:
    description: "image name"
    required: true
  artifact:
    description: "artifact name"
    required: true

outputs:
  image:
    description: "Loaded Docker Image Name"
    value: ${{ steps.load-image.outputs.image }}

runs:
  using: "composite"
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: .image

    - name: Load Docker Image
      shell: bash
      id: load-image
      run: |
        # convert inputs.image to filename 
        filename="${{ inputs.image }}"
        filename="${filename//\//-}"
        filename="${filename//./-}"
        filename="${filename//:/-}"
        filename=".image/${filename}.tar"
        
        echo "::notice:: Loading Docker Image from ${filename}..."               
        image=$(docker load --input ${filename} | grep 'Loaded image:' | awk '{print $3}')
        
        echo "::notice:: Docker Image loaded as $image"
        echo "image=$image" >> $GITHUB_OUTPUT
