name: "Explode Branch Into Version"
description: "Get Major, Minor, Patch, Pre- and Postfix of a given branch"
inputs:
  branch:
    description: "branch name"
    required: true

outputs:
  branch:
    description: "In case of matching patterns identically with given branch"
    value: ${{ steps.extract.outputs.branch }}
  prefix:
    description: "Prefix for given branch"
    value: ${{ steps.extract.outputs.prefix }}
  major:
    description: "Major version for given branch"
    value: ${{ steps.extract.outputs.major }}
  minor:
    description: "Minor version for given branch"
    value: ${{ steps.extract.outputs.minor }}
  patch:
    description: "Patch version for given branch"
    value: ${{ steps.extract.outputs.patch }}
  postfix:
    description: "Postfix for given branch"
    value: ${{ steps.extract.outputs.postfix }}

runs:
  using: "composite"
  steps:
    - name: "Checkout Draftmode Scripts"
      id: script
      uses: draftm0de/kernel.deployment/.github/actions/check-out-scripts@main

    - name: "Explode Branch Name"
      id: extract
      shell: bash
      run: |
        echo "::group::Converting branch ${{ inputs.branch }}"
        
        path=${{ steps.script.outputs.path }}
        source ./${path}/converter/explode-git-branch-to-version.sh "${{ inputs.branch }}"
        
        echo "> branch: $BRANCH"        
        echo "> prefix: $PREFIX"
        echo "> major: $MAJOR"
        echo "> minor: $MINOR"
        echo "> patch: $PATCH"
        echo "> postfix: $POSTFIX"
        
        echo "::endgroup::"
        echo "branch=$BRANCH" >> $GITHUB_OUTPUT          
        echo "prefix=$PREFIX" >> $GITHUB_OUTPUT
        echo "major=$MAJOR" >> $GITHUB_OUTPUT
        echo "minor=$MINOR" >> $GITHUB_OUTPUT
        echo "patch=$PATCH" >> $GITHUB_OUTPUT
        echo "postfix=$POSTFIX" >> $GITHUB_OUTPUT   
