name: "Load Docker Image From Artifact"
description: "Load docker image from a given artifact"
inputs:
  image:
    description: "image name"
    required: true
  artifact:
    description: "artifact name"
    required: true

outputs:
  image:
    description: "Loaded Docker Image Name"
    value: ${{ steps.get-image.outputs.image }}

runs:
  using: "composite"
  steps:
    - name: "Download Artifact"
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: ".image"

    - name: "Convert Image Name"
      id: get-file-name
      uses: draftm0de/kernel.deployment/.github/actions/dto-convert-image-name-to-file@main
      with:
        image: ${{ inputs.image }}

    - name: "Loading Docker Image"
      shell: bash
      id: get-image
      run: |
        echo "::notice:: Loading docker image from file..."

        file=".image/${{ steps.get-file-name.outputs.file }}"
        image=$(docker load --input ${file} | grep 'Loaded image:' | awk '{print $3}')
        echo "::notice:: > loaded image: $image"        
                
        echo "::notice:: Docker image loaded."
        echo "image=$image" >> $GITHUB_OUTPUT
