name: "Load Docker Image From Artifact"
description: "Load docker image from a given artifact"
inputs:
  image:
    description: "image name"
    required: true
  artifact:
    description: "artifact name"
    required: true

outputs:
  image:
    description: "Loaded Docker Image Name"
    value: ${{ steps.load-image.outputs.image }}

runs:
  using: "composite"
  steps:
    - name: "Download Artifact"
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}

    - name: "Convert Image Name"
      id: get-file-name
      uses: draftm0de/kernel.deployment/.github/actions/convert-image-to-file-name@main
      with:
        image: ${{ inputs.image }}

    - name: "Load Image from Artifact"
      shell: bash
      id: load-image
      run: |       
        echo "::notice:: Loading docker image from file..."               
        
        image=$(docker load --input .image/${{ steps.get-file-name.outputs.file }} | grep 'Loaded image:' | awk '{print $3}')
        echo "::notice:: > image: $image"
        
        echo "::notice:: Docker image loaded."
        echo "image=$image" >> $GITHUB_OUTPUT
