name: "Get Docker Manifest Property"
description: "Get Docker Manifest .Config.Digest"
inputs:
  image:
    description: "Docker image with tag"
    required: true
  property:
    description: "jq pattern for a property"
    required: true
outputs:
  property:
    description: "Value for the given property"
    value: ${{ steps.get-value.outputs.property }}

runs:
  using: "composite"
  steps:
    - name: "Getting Property From Manifest"
      shell: bash
      id: get-value
      run: |
        echo "::group::Getting Property From Manifest..."
        response=$(docker manifest inspect ${{ inputs.image }} 2>/dev/null)
        if [ $? -eq 0 ]; then
          echo "> manifest found"
          property=$(echo "$response" | jq -r '${{ inputs.property }}')
          if [ "$property" != "null" ]; then
            echo "> property: $property"
            echo "property=$property" >> $GITHUB_OUTPUT
          else
            echo "::error::${{ inputs.property }} not found in manifest"
          fi
        else
          echo "::error::manifest for ${{ inputs.image }} not found"
        fi
        echo "::endgroup::"

