name: "Build Image Tags"
description: "Build Image Tags"
inputs:
  source:
    description: "source branch"
    required: true
  target:
    description: "branch to be merged into"
    required: true

outputs:
  tags:
    description: "tags to be use for image"
    value: ${{ steps.get-image-tags.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: "Convert target branch into version"
      shell: bash
      id: target
      uses: draftm0de/kernel.deployment/.github/actions/convert-branch-to-version@main
      with:
        branch: ${{ inputs.target }}

    - name: "Convert source branch into version"
      shell: bash
      id: source
      uses: draftm0de/kernel.deployment/.github/actions/convert-branch-to-version@main
      with:
        branch: ${{ inputs.source }}

    - name: "Tag Branches"
      shell: bash
      id: get-image-tags
      run: |
        echo "::notice:: Building Image Tags..."
        
        tags=()
        if [ "${{ steps.target.outputs.branch }}" == "${{ inputs.target }}" ]; then
          echo "::notice::> use target branch (matches version patterns)"
          tags+=("${{ inputs.target }}")
        fi
        
        if [ "${{ steps.source.outputs.branch }}" == "${{ inputs.source }}" ]; then
          echo "::notice::> use source branch (matches version patterns)"
          tags+=("${{ inputs.source }}")
        fi
        echo "tags=${tags[*]}" >> $GITHUB_OUTPUT
        echo "::notice::Image tags built.
