name: "Scan Docker Image"
description: "Scan Vulnerability for Docker Image"
inputs:
  image:
    description: "image name"
    required: true
  config:
    description: "config file"
    required: true
  docker_username:
    description: "docker username"
    required: true
  docker_password:
    description: "docker password"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Prepare Scout Arguments"
      shell: bash
      id: arguments
      run: |
        echo "::notice:: Preparing Scout Arguments..."
        source ${{ inputs.config }}
        
        echo "::notice:: > receive arguments"
        echo "::notice:: > > severity: ${severity}"
        echo "::notice:: > > command: ${command}"
        echo "::notice:: > > ignore_base: ${ignore_base}"
                
        severity="${severity:-critical,high}"
        command="${command:-quickview}"
        echo "::notice:: > taken arguments"
        echo "::notice:: > > severity: ${severity}"
        echo "::notice:: > > command: ${command}"        
        
        echo "severity=$severity" >> $GITHUB_OUTPUT
        echo "command=$command" >> $GITHUB_OUTPUT
        if [[ "$ignore_base" == "true" ]]; then
          echo "ignore_base=true" >> $GITHUB_OUTPUT
        else
          echo "ignore_base=false" >> $GITHUB_OUTPUT
        fi
        echo "::notice:: Scout arguments prepared."

    - name: "Login To Docker Hub"
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: "Scan With Docker Scout"
      uses: docker/scout-action@v1
      with:
        image: ${{ inputs.image }}
        only-severities: ${{ steps.arguments.outputs.severity }}
        command: ${{ steps.arguments.outputs.command }}
        ignore-base: ${{ steps.arguments.outputs.ignore_base }}
