name: "Explode Branch Into Version"
description: "Get Major, Minor, Patch, Pre- and Postfix of a given branch"
inputs:
  branch:
    description: "branch name"
    required: true

outputs:
  branch:
    description: "In case of matching patterns identically with given branch"
    value: ${{ steps.extract.outputs.branch }}
  prefix:
    description: "Prefix for given branch"
    value: ${{ steps.extract.outputs.prefix }}
  major:
    description: "Major version for given branch"
    value: ${{ steps.extract.outputs.major }}
  minor:
    description: "Minor version for given branch"
    value: ${{ steps.extract.outputs.minor }}
  patch:
    description: "Patch version for given branch"
    value: ${{ steps.extract.outputs.patch }}
  postfix:
    description: "Postfix for given branch"
    value: ${{ steps.extract.outputs.postfix }}

runs:
  using: "composite"
  steps:
    - name: Extract Branch Name
      id: extract
      shell: bash
      run: |
        # Extract the target branch name
        branch="${{ inputs.branch }}"

        # Regex pattern to capture major, minor, patch, and optional postfix
        REGEX="^(v)?([0-9]+)(\.[0-9]+)?(\.[0-9]+)?(-[a-zA-Z0-9]+)?$"
        
        # Match branch name against the regex
        if [[ "$branch" =~ $REGEX ]]; then
          prefix="${BASH_REMATCH[1]}"
          major="${BASH_REMATCH[2]}"
          minor="${BASH_REMATCH[3]}"
          patch="${BASH_REMATCH[4]}"
          postfix="${BASH_REMATCH[5]}"
        
          # remove leading .
          minor="${minor#.}"
          patch="${patch#.}"

          echo "prefix=$prefix" >> $GITHUB_OUTPUT
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor=$minor" >> $GITHUB_OUTPUT
          echo "patch=$patch" >> $GITHUB_OUTPUT
          echo "postfix=$postfix" >> $GITHUB_OUTPUT
          echo "branch=$branch" >> $GITHUB_OUTPUT
        fi
