name: Check Artifact

on:
  workflow_call:
    inputs:
      artifact:
        description: "artifact name"
        required: true
        type: string

jobs:
  check-artifact:
    runs-on: ubuntu-latest
    outputs:
      artifact_exists: ${{ steps.check.outputs.artifact_exists }}
    steps:
      - name: Attempt to download artifact
        id: check
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
        continue-on-error: true

      - name: Set existence output to true
        if: ${{ success() }}
        run: echo "artifact_exists=true" >> $GITHUB_OUTPUT

      - name: Set existence output to false
        if: ${{ failure() }}
        run: echo "artifact_exists=false" >> $GITHUB_OUTPUT
