name: Build Docker Image

on:
  workflow_call:
    inputs:
      namespace:
        description: "Image (Namespace)"
        required: true
        type: string      
      image:
        description: "Image (Name)"
        required: true
        type: string      
      context:
        description: "Docker build context/path"
        required: true
        type: string
      build_target:
        description: "Image Built (Target)"
        required: false
        type: string
      build_args_file:
        description: "Filename to be used for --build-args"
        required: false
        type: string
      tag_level:
        description: "Levels for tagging an image"
        required: true
        type: number
      tag_base_version_file:
         description: "Filename within the Base Version for auto tagging"
         required: false
         type: string
      protected_tag:
        description: "Protect against duplicate SHA"
        type: string
        required: false
        default: "false"
    secrets:
      docker_username:
        description: "Docker Login (Username)"
        required: true
      docker_password:
        description: "Docker Login (Password)"
        required: true

env:
  IMAGE_ARTIFACT_NAME: image-artifact

jobs:
  test:
    runs-on: ubuntu-20.04
    steps: 
      - name: Download the Docker Image From Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_ARTIFACT_NAME }}

      - name: Get Source
        run: ls -la

#      - name: Load the Docker image
#        if: ${{ needs.build.outputs.image_artifact_file != '' }}
#        run: docker load -i ${{ needs.build.outputs.image_artifact_file }}        
          
#      - name: Scan Docker Image
#        uses: aquasecurity/trivy-action@0.20.0
#        with:
#          input: '/github/workspace/${{ steps.image-save.outputs.image_artifact_file }}'
#          severity: 'CRITICAL,HIGH'          
