name: Build Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "Image Name"
        required: true
        type: string
      context:
        description: "Mount from child child repository (compare with docker context)"
        required: true
        type: string
      build_args:
        description: "Filename to be used for --build-args (relative to mount)"
        required: false
        type: string

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker.sh script
        env:
          IMAGE: ${{ inputs.image }}
          CONTEXT: ${{ inputs.context }}
          BUILD_ARGS_FILE: ${{ inputs.build_args }}
        run: |      
          BUILD_ARGS_FILE=${BUILD_ARGS_FILE:-.build_args}
          # can you get the context 
          echo "child context:"
          ls ${CONTEXT} -la
          # get current repository content
          echo "own context:"
          ls -la
