name: Build Docker Image

on:
  workflow_call:
    inputs:
      namespace:
        description: "Image (Namespace)"
        required: true
        type: string      
      image:
        description: "Image (Name)"
        required: true
        type: string      
      context:
        description: "Docker build context/path"
        required: true
        type: string
      build_target:
        description: "Image Built (Target)"
        required: false
        type: string
      build_args_file:
        description: "Filename to be used for --build-args"
        required: false
        type: string
      tag_level:
        description: "Levels for tagging an image"
        required: true
        type: number
      tag_base_version_file:
         description: "Filename within the Base Version for auto tagging"
         required: false
         type: string
      protected_tag:
        description: "Protect against duplicate SHA"
        type: string
        required: false
        default: "false"
    secrets:
      docker_username:
        description: "Docker Login (Username)"
        required: true
      docker_password:
        description: "Docker Login (Password)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Uut Own (parent) Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        id: image-build
        env:
          BUILD_ARGS_FILE: ${{ inputs.context }}/${{ inputs.build_args_file }}
        run: |
          echo "::Notice:: Build image..."
          if [ -d "${{ inputs.context }}" ]; then
            IMAGE_TAG="latest"
            BUILD_TARGET="${{ inputs.build_target }}"
            if [ -n "${BUILD_TARGET}" ]; then
              echo "::debug::- Build with --target: $BUILD_TARGET"
              IMAGE_TAG="${BUILD_TARGET}-${IMAGE_TAG}"
              BUILD_TARGET=" --target $IMAGE_BUILD_TARGET              
            fi             
            IMAGE="${{ inputs.namespace }}/${{ inputs.image }}:${IMAGE_TAG}"
            if [ -f "$BUILD_ARGS_FILE" ]; then
              echo "::debug::- Build with --build-args: $BUILD_ARGS_FILE"
              BUILD_ARGS=$(cat "$BUILD_ARGS_FILE" | awk -F "=" '{ print "--build-arg " $1"="$2;}' | xargs)
              docker build --tag ${IMAGE}${BUILD_TARGET} $BUILD_ARGS ${{ inputs.context }}
            else
              docker build --tag ${IMAGE}${BUILD_TARGET} ${{ inputs.context }}
            fi
          else
            echo "::error:: Directory ${{ inputs.context }} does not exist"
            exit 1
          fi
          echo "::notice:: > build successfully"
          echo "IMAGE=${IMAGE}" >> $GITHUB_OUTPUT
          echo "IMAGE_FILE=${{ inputs.image }}-${IMAGE_TAG}" >> $GITHUB_OUTPUT
          
      - name: Save Docker Image
        id: image-store
        run: |
          IMAGE="${{ steps.image-build.outputs.IMAGE }}"
          IMAGE_FILE="${{ steps.image-build.outputs.IMAGE_FILE }}.tar"
          docker save -o $IMAGE_FILE $IMAGE
          echo "IMAGE_FILE=$IMAGE_FILE" >> $GITHUB_OUTPUT

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.image-build.outputs.IMAGE }}
          path: ${{ steps.image-store.outputs.IMAGE_FILE }}         
  test:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Scan Docker Image
        run: |
          docker images
          
