name: Build Docker Image

on:
  workflow_call:
    inputs:
      namespace:
        description: "Image (Namespace)"
        required: true
        type: string      
      image:
        description: "Image (Name)"
        required: true
        type: string      
      context:
        description: "Docker build context/path"
        required: true
        type: string
      build_target:
        description: "Image Built (Target)"
        required: false
        type: string
      build_args_file:
        description: "Filename to be used for --build-args"
        required: false
        type: string
      tag_level:
        description: "Levels for tagging an image"
        required: true
        type: number
      tag_base_version_file:
         description: "Filename within the Base Version for auto tagging"
         required: false
         type: string
      protected_tag:
        description: "Protect against duplicate SHA"
        type: string
        required: false
        default: "false"
# for security scan
#      context:
#        description: "Docker build context/path"
#        required: true
#        type: string
      artifact_file:
        description: "Image Artifact File"
        type: string
        required: false
        default: "kernel.caddy.tar"      
      scan_severity:
        description: "Image Scan Severities"
        type: string
        required: false
        default: "CRITICAL,HIGH"
    secrets:
      docker_username:
        description: "Docker Login (Username)"
        required: true
      docker_password:
        description: "Docker Login (Password)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      built_image_name: ${{ steps.image-build.outputs.built_image_name }}
    steps:
      - name: Check Out Own (parent) Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        id: image-build
        env:
          BUILD_ARGS_FILE: ${{ inputs.context }}/${{ inputs.build_args_file }}
        run: |
          echo "::Notice:: Build image..."
          if [ -d "${{ inputs.context }}" ]; then
            IMAGE_TAG="latest"
            BUILD_TARGET="${{ inputs.build_target }}"
            if [ -n "${BUILD_TARGET}" ]; then
              echo "::debug::- Build with --target: $BUILD_TARGET"
              IMAGE_TAG="${BUILD_TARGET}-${IMAGE_TAG}"
              # leading space required, concatination in docker build command
              BUILD_TARGET=" --target $BUILD_TARGET"            
            fi             
            IMAGE="${{ inputs.namespace }}/${{ inputs.image }}:${IMAGE_TAG}"
            if [ -f "$BUILD_ARGS_FILE" ]; then
              echo "::debug::- Build with --build-args: $BUILD_ARGS_FILE"
              BUILD_ARGS=$(cat "$BUILD_ARGS_FILE" | awk -F "=" '{ print "--build-arg " $1"="$2;}' | xargs)
              docker build --tag ${IMAGE}${BUILD_TARGET} $BUILD_ARGS ${{ inputs.context }}
            else
              docker build --tag ${IMAGE}${BUILD_TARGET} ${{ inputs.context }}
            fi
          else
            echo "::error:: Directory ${{ inputs.context }} does not exist"
            exit 1
          fi
          echo "::notice:: > build successfully"
          echo "::notice:: Save Docker Image"
          IMAGE_ARTIFACT_FILE="${{ inputs.image }}.tar"
          docker save -o ${IMAGE_ARTIFACT_FILE} ${IMAGE}         
          echo "::notice:: > save successfully"
          echo "image_artifact_file=${IMAGE_ARTIFACT_FILE}" >> $GITHUB_OUTPUT

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.image-build.outputs.image_artifact_file }}
          
  test:
    runs-on: ubuntu-20.04
    needs: build
    steps: 
      - name: Check Out Own (parent) Repository
        uses: actions/checkout@v4

      - name: Prepare/Observe .trivyignore File
        id: trivy-ignore-file
        run: |
          TRIVY_IGNORE_FILE="${{ inputs.context }}/.trivyignore"
          if [ -f "$TRIVY_IGNORE_FILE" ]; then
            echo "::notice:: > Use $TRIVY_IGNORE_FILE"
          else
            echo "::notice:: > Create Empty $TRIVY_IGNORE_FILE"
            touch "$TRIVY_IGNORE_FILE"
          fi
          echo "trivy_ignore_file=${TRIVY_IGNORE_FILE}" >> $GITHUB_OUTPUT
        
      - name: Download the Docker Image From Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.artifact_file }}   

      - name: List
        run: ls -la
          
#      - name: Scan Docker Image
#        uses: aquasecurity/trivy-action@0.20.0
#        with:
#          input: ${{ inputs.artifact_file }}
#          severity: ${{ inputs.scan_severity }}
#        env:
#          TRIVY_IGNORE_FILE: ${{ steps.trivy-ignore-file.outputs.trivy_ignore_file }}
        
