name: Build Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "Image Name"
        required: true
        type: string
      mount:
        description: "Mount from child child repository (compare with docker context)"
        required: true
        type: string
      build_args:
        description: "Filename to be used for --build-args (relative to mount)"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker.sh script
        env:
          IMAGE: ${{ inputs.image }}
          MOUNT: ${{ inputs.mount }}
          BUILD_ARGS_FILE: ${{ inputs.build_args }}
        run: |      
          BUILD_ARGS_FILE=${BUILD_ARGS_FILE:-.build_args}
          # can you get the context 
          echo ls ${MOUNT} -la
          # execute docker 
          if [ -f "${MOUNT}/${BUILD_ARGS_FILE}" ]; then
            ./docker.sh -t $IMAGE --build-args=${MOUNT}/${BUILD_ARGS_FILE} ${MOUNT}
          else
            docker build -t $IMAGE ${MOUNT}
          fi 
