name: Build Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "image name"
        type: string
        required: true
      target:
        description: "build --target"
        type: string
        required: false
      context:
        description: "build context"
        type: string
        required: false
        default: "."
      options:
        description: "additional build options"
        type: string
        required: false
      build_args_file:
        description: "--build-args from file"
        type: string
        required: false
      artifact:
        description: "artifact name"
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: "Build Docker Image"
        id: build-image
        uses: ./github/actions/image-build@main
        with:
          image: ${{ inputs.image }}
          target: ${{ inputs.target }}
          context: ${{ inputs.context }}
          options: ${{ inputs.options }}
          build_args_file: ${{ inputs.build_args_file }}

      - name: "Save Docker Image"
        if: ${{ inputs.artifact }}
        uses: ./github/actions/image-save@main
        with:
          image: ${{ inputs.image }}
          artifact: ${{ inputs.artifact }}
