name: Build Docker Image

on:
  workflow_call:
    inputs:
      namespace:
        description: "Image (Namespace)"
        required: true
        type: string      
      image:
        description: "Image (Name)"
        required: true
        type: string
      context:
        description: "Docker build context/path"
        required: true
        type: string
      build_args_file:
        description: "Filename to be used for --build-args"
        required: false
        type: string
      tag_level:
        description: "Levels for tagging an image"
        required: true
        type: number
      tag_base_version_file:
         description: "Filename within the Base Version for auto tagging"
         required: false
         type: string
      protected_tag:
        description: "Protect against duplicate SHA"
        type: string
        required: false
        default: "false"
    secrets:
      docker_username:
        description: "Docker Login (Username)"
        required: true
      docker_password:
        description: "Docker Login (Password)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Uut Own (parent) Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        env:
          BUILD_ARGS_FILE: ${{ inputs.build_args_file }}
        run: |
          echo "::Notice:: Build image..."
          if [ -d "${{ inputs.context }}" ]; then
            IMAGE="${{ inputs.namespace }}/${{ inputs.image }}:latest"
            if [ -f "$BUILD_ARGS_FILE" ]; then
              echo "::notice::- Build with --build-args"
              BUILD_ARGS=$(cat "$BUILD_ARG_FILE" | awk -F "=" '{ print "--build-arg " $1"="$2;}' | xargs)
              docker build --tag $IMAGE $BUILD_ARGS ${{ inputs.context }}
            else
              docker build --tag $IMAGE ${{ inputs.context }}
            fi
          else
            echo "::error:: Directory ${{ inputs.context }} does not exist"
            exit 1
          fi
          echo "::notice:: > build successfully"
       
          
