name: Build Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "image name"
        required: true
        type: string
      context:
        description: "Context (Path) for build command"
        required: true
        type: string
      build_args:
        description: "filename for --build-args"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout own repository and map as main
        uses: actions/checkout@v4

      - name: Use the passed argument
        env:
          CONTEXT: ${{ inputs.context }}
          BUILD_ARGS_FILE: ${{ inputs.build_args }}
        run: |      
          BUILD_ARGS_FILE=${BUILD_ARGS_FILE:-.build_args}
          if [ -f "$BUILD_ARGS_FILE" ]; then
            ./docker.sh --build-args=$BUILD_ARGS_FILE $CONTEXT
          else
            docker build $CONTEXT
          fi 
