name: Build Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "Image Name"
        required: true
        type: string
      context:
        description: "Mount from child child repository (compare with docker context)"
        required: true
        type: string
      build_args:
        description: "Filename to be used for --build-args (relative to mount)"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker.sh script
        env:
          IMAGE: ${{ inputs.image }}
          CONTEXT: ${{ inputs.context }}
          BUILD_ARGS_FILE: ${{ inputs.build_args }}
        run: |      
          BUILD_ARGS_FILE=${BUILD_ARGS_FILE:-.build_args}
          # can you get the context 
          ls content -la
          # execute docker 
          if [ -f "${CONTEXT}/${BUILD_ARGS_FILE}" ]; then
            ./docker.sh -t $IMAGE --build-args=${CONTEXT}/${BUILD_ARGS_FILE} ${MOUNT}
          else
            docker build -t $IMAGE ${CONTEXT}
          fi 
