name: Build Docker Image

on:
  workflow_call:
    inputs:
      namespace:
        description: "Image Namespace"
        required: true
        type: string      
      image:
        description: "Image Name"
        required: true
        type: string
      context:
        description: "Docker build path"
        required: true
        type: string
      build_args:
        description: "Filename to be used for --build-args"
        required: false
        type: string

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the kernel.deployment repository
        uses: actions/checkout@v4
        with:
          repository: draftm0de/kernel.deployment
          path: parent

      - name: Check out the own (parent) repository
        uses: actions/checkout@v4
        with:
          path: content

      - name: docker build
        env:
          BUILD_ARGS_FILE: ${{ inputs.build_args }}
        run: |
          CONTEXT="content/${{ inputs.context }}"
          TAG="--tag ${{ inputs.namespace }}/${{ inputs.image }}"
          BUILD_ARGS_FILE="$CONTEXT/${BUILD_ARGS_FILE:-.build_args}"
          if [ -f "$BUILD_ARGS_FILE" ]; then
            ./parent/docker.sh build $TAG --build-args=$BUILD_ARGS_FILE $CONTEXT
          else
            docker build $TAG $CONTEXT
          fi
          
      - name: Save(Tar) Docker Image
        run: docker save -o content/image.tar ${{ inputs.namespace }}/${{ inputs.image }}

      - name: Scan with Clair
        uses: quay/clair-action@main
        with:
          image-path: content/image.tar
          format: sarif
          output: clair_results.sarif

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: clair_results.sarif
