name: Build Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "Docker image without tag"
        type: string
        required: true
      target:
        description: "Build --target"
        type: string
        required: false
        default: ""
      context:
        description: "Build context"
        type: string
        required: false
        default: "."
      options:
        description: "Additional build options"
        type: string
        required: false
        default: ""
      build_args_file:
        description: "--build-args from file"
        type: string
        required: false
        default: ""
      reproducible:
        description: "Build reproducible image"
        type: boolean
        required: false
        default: false
      artifact:
        description: "Artifact name"
        type: string
        required: false
        default: ""
    outputs:
      digest:
        description: "Build image digest"
        value: ${{ jobs.build.outputs.digest }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build-image.outputs.digest }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: "Build Docker Image"
        id: build-image
        uses: draftm0de/kernel.deployment/.github/actions/image-build@main
        with:
          image: ${{ inputs.image }}
          target: ${{ inputs.target }}
          context: ${{ inputs.context }}
          options: ${{ inputs.options }}
          build_args_file: ${{ inputs.build_args_file }}
          reproducible: ${{ inputs.reproducible }}

      - name: "Save Docker Image"
        if: ${{ inputs.artifact && inputs.artifact != '' }}
        uses: draftm0de/kernel.deployment/.github/actions/image-save@main
        with:
          image: ${{ inputs.image }}
          artifact: ${{ inputs.artifact }}
