name: Build Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "Image Name"
        required: true
        type: string
      context:
        description: "Mount from child child repository (compare with docker context)"
        required: true
        type: string
      build_args:
        description: "Filename to be used for --build-args (relative to mount)"
        required: false
        type: string

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the kernel.deployment repository
        uses: actions/checkout@v4
        with:
          repository: draftm0de/kernel.deployment
          path: parent

      - name: Check out the own (parent) repository
        uses: actions/checkout@v4
        with:
          path: content
          
      - name: docker build
        env:
          IMAGE: ${{ inputs.image }}
          CONTEXT: ${{ inputs.context }}
          BUILD_ARGS_FILE: ${{ inputs.build_args }}
        run: |
          CONTEXT="content/${CONTEXT}"
          BUILD_ARGS_FILE="${BUILD_ARGS_FILE:-.build_args}"
          if [ -f "${CONTEXT}/${BUILD_ARGS_FILE}" ]; then
            echo ".build-args file found"
            ./parent/docker.sh --tag $IMAGE --build-args=${CONTEXT}/${BUILD_ARGS_FILE} ${CONTEXT}
          else
            echo ".build-args file not found"
            docker build --tag ${IMAGE} ${CONTEXT}
          fi
            
