name: Build Docker Image

on:
  workflow_call:
    inputs:
      namespace:
        description: "Image (Namespace)"
        required: true
        type: string      
      image:
        description: "Image (Name)"
        required: true
        type: string      
      context:
        description: "Docker build context/path"
        required: true
        type: string
      build_target:
        description: "Image Built (Target)"
        required: false
        type: string
      build_args_file:
        description: "Filename to be used for --build-args"
        required: false
        type: string
      tag_level:
        description: "Levels for tagging an image"
        required: true
        type: number
      tag_base_version_file:
         description: "Filename within the Base Version for auto tagging"
         required: false
         type: string
      protected_tag:
        description: "Protect against duplicate SHA"
        type: string
        required: false
        default: "false"
    secrets:
      docker_username:
        description: "Docker Login (Username)"
        required: true
      docker_password:
        description: "Docker Login (Password)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Uut Own (parent) Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        id: image-build
        env:
          BUILD_ARGS_FILE: ${{ inputs.context }}/${{ inputs.build_args_file }}
        run: |
          echo "::Notice:: Build image..."
          if [ -d "${{ inputs.context }}" ]; then
            IMAGE_TAG="latest"
            BUILD_TARGET="${{ inputs.build_target }}"
            if [ -n "${BUILD_TARGET}" ]; then
              echo "::debug::- Build with --target: $BUILD_TARGET"
              IMAGE_TAG="${BUILD_TARGET}-${IMAGE_TAG}"
              # leading space required, concatination in docker build command
              BUILD_TARGET=" --target $IMAGE_BUILD_TARGET"            
            fi             
            IMAGE="${{ inputs.namespace }}/${{ inputs.image }}:${IMAGE_TAG}"
            if [ -f "$BUILD_ARGS_FILE" ]; then
              echo "::debug::- Build with --build-args: $BUILD_ARGS_FILE"
              BUILD_ARGS=$(cat "$BUILD_ARGS_FILE" | awk -F "=" '{ print "--build-arg " $1"="$2;}' | xargs)
              docker build --tag ${IMAGE}${BUILD_TARGET} $BUILD_ARGS ${{ inputs.context }}
            else
              docker build --tag ${IMAGE}${BUILD_TARGET} ${{ inputs.context }}
            fi
          else
            echo "::error:: Directory ${{ inputs.context }} does not exist"
            exit 1
          fi
          echo "::notice:: > build successfully"
          echo "BUILT_IMAGE_NAME=${IMAGE}" >> $GITHUB_OUTPUT
          echo "BUILT_IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          
      - name: Save Docker Image
        id: image-save
        run: |
          IMAGE_SAVE_NAME="${{ inputs.image }}-${{ steps.image-build.outputs.BUILT_IMAGE_TAG }}"
          IMAGE_SAVE_FILE="${IMAGE_SAVE_NAME}.tar"
          docker save -o ${IMAGE_SAVE_FILE} ${{ steps.image-build.outputs.BUILT_IMAGE_NAME }}
          echo "IMAGE_ARTIFACT_NAME=${IMAGE_SAVE_NAME}" >> $GITHUB_OUTPUT
          echo "IMAGE_ARTIFACT_FILE=${IMAGE_SAVE_FILE}" >> $GITHUB_OUTPUT

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.image-save.outputs.IMAGE_SAVE_NAME }}
          path: ${{ steps.image-save.outputs.IMAGE_SAVE_FILE }}
          
  test:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Download the Docker Image From Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.image-save.outputs.IMAGE_SAVE_NAME }}

      - name: Load the Docker image
        run: docker load -i ${{ needs.build.image-save.outputs.IMAGE_SAVE_FILE }}        
          
      - name: Scan Docker Image
        run: |
          docker images
          
