name: Build Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "Image Name"
        required: true
        type: string
      context:
        description: "Mount from child child repository (compare with docker context)"
        required: true
        type: string
      build_args:
        description: "Filename to be used for --build-args (relative to mount)"
        required: false
        type: string

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the parent repository (this repo)
      - name: Check out the parent repository
        uses: actions/checkout@v4
        with:
          repository: draftm0de/kernel.deployment  # Parent repository
          path: parent  # Checkout the parent repo into 'parent' folder

      # Step 2: Checkout the child repository manually (optional if needed)
      - name: Check out the child repository
        uses: actions/checkout@v4
        with:
          path: content  # Checkout into 'content' folder          
          
      # Step 3: List files in the parent directory (for debugging)
      - name: List parent directory
        run: ls parent -la

      # Step 4: List files in the child directory (for debugging)
      - name: List content directory
        run: ls content -la        

      # Step 3: List files in the child directory (for debugging)
      - name: Run docker.sh script
        env:
          IMAGE: ${{ inputs.image }}
          CONTEXT: ${{ inputs.context }}
          BUILD_ARGS_FILE: ${{ inputs.build_args }}
        run: ls content -la
