name: Push Docker Image

on:
  workflow_call:
    inputs:
      source:
        description: "source branch"
        type: string
        required: false
      target:
        description: "branch to be merged into"
        type: string
        required: false
      image:
        description: "image name"
        required: true
        type: string
      artifact:
        description: "artifact name"
        required: false
        type: string
    secrets:
      DOCKER_USERNAME:
        required: false
      DOCKER_PASSWORD:
        required: false

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: "Build Image Tags"
        id: get-image-tags
        uses: draftm0de/kernel.deployment/.github/actions/build-image-tags@main
        with:
          source: ${{ inputs.source || github.ref_name }}
          target: ${{ inputs.target || github.event.pull_request.base.ref }}

      - name: "Load Docker Image From Artifact"
        id: load-image
        if: ${{ inputs.artifact }}
        uses: draftm0de/kernel.deployment/.github/actions/image-load@main
        with:
          image: ${{ inputs.image }}
          artifact: ${{ inputs.artifact }}

      - name: "Tag and Push Image"
        if: ${{ steps.get-image-tags.outputs.tags }}
        run: |
          echo "::notice::Tagging and Pushing Image..."
          while IFS= read -r tag; do
            image="${{ secrets.DOCKER_USERNAME }}/${tag}"
            echo "::notice::$tag"
            echo "::notice::> tag image: $tag"
            echo "::notice::> push image: $image"
          done <<< "${{ steps.get-image-tags.outputs.tags }}"         
