name: Push Commit Tag

on:
  workflow_call:
    inputs:
      target_branch:
        description: "Branch to be merged Into"
        required: false
        type: string

jobs:
  tag-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: "Preparing Arguments"
        run: |
          echo "::notice:: Preparing Arguments"
          if [ -n "$(git tag --contains HEAD)" ]; then
            echo "::warning:: commit already has a tag"
            exit 0
          fi
          if [ -n "${{ inputs.target_branch }}" ]; then
            target="${{ inputs.target_branch }}"
            echo "::notice:: > target base on argument: $target"
          elif [ -n "${{ github.event.pull_request.base.ref }}" ]; then
            target="${{ github.event.pull_request.base.ref }}"
            echo "::notice:: > target based on pull.event: $target"
          else
            echo "::warning:: no target branch given"
            exit 0
          fi
          
          if [ -n "${{ github.event.pull_request.head.ref }}" ]; then
            source="${{ github.event.pull_request.head.ref }}"
            echo "::notice:: > source branch based on pull.event: $source"
          elif [ -n "${{ github.ref_name }}" ]; then
            source="${{ github.ref_name }}"
            echo "::notice:: > source branch based on github.ref_name: $source"          
          else
            echo "::warning:: no source branch given"
            exit 0                    
          fi
          
          echo "::notice:: Arguments prepared."
          echo "SOURCE_BRANCH=$source" >> $GITHUB_ENV
          echo "TARGET_BRANCH=$target" >> $GITHUB_ENV

      - name: "Explode Target Branch"
        if: ${{ env.TARGET_BRANCH }}
        id: explode-target
        uses: draftm0de/kernel.deployment/.github/actions/explode-branch@main
        with:
          branch: ${{ env.TARGET_BRANCH }}

      - name: "Explode Source Branch"
        if: ${{ env.SOURCE_BRANCH }}
        id: explode-source
        uses: draftm0de/kernel.deployment/.github/actions/explode-branch@main
        with:
          branch: ${{ env.SOURCE_BRANCH }}

      - name: "Commit: Get Latest Tag"
        id: latest-tag
        # source branch does not match version patterns
        # target matches version patterns
        # target has no patch version
        if: ${{ steps.explode-target.outputs.branch && !steps.explode-source.outputs.branch && !steps.explode-target.outputs.patch}}
        uses: draftm0de/kernel.deployment/.github/actions/tag-get-latest@main
        with:
          prefix: ${{ steps.explode-target.outputs.prefix }}
          major: ${{ steps.explode-target.outputs.major }}
          minor: ${{ steps.explode-target.outputs.minor }}
          patch: ${{ steps.explode-target.outputs.patch }}
          postfix: ${{ steps.explode-target.outputs.postfix }}

      - name: "Commit: Explode Latest Tag"
        if: ${{ steps.latest-tag.outputs.tag }}
        id: explode-latest-tag
        uses: draftm0de/kernel.deployment/.github/actions/explode-branch@main
        with:
          branch: ${{ steps.latest-tag.outputs.tag }}

      - name: "Commit: Increase Latest Tag"
        id: increase-commit-tag
        if: ${{ steps.explode-latest-tag.outputs.branch }}
        uses: draftm0de/kernel.deployment/.github/actions/tag-increase-version@main
        with:
          prefix: ${{ steps.explode-latest-tag.outputs.prefix }}
          major: ${{ steps.explode-latest-tag.outputs.major }}
          minor: ${{ steps.explode-latest-tag.outputs.minor }}
          patch: ${{ steps.explode-latest-tag.outputs.patch }}
          postfix: ${{ steps.explode-latest-tag.outputs.postfix }}

      - name: "Commit: Apply Tag"
        if: ${{ steps.increase-commit-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: Tagging Commit..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # git tag ${{ steps.increase-commit-tag.outputs.tag }}
          # git push origin ${{ steps.increase-commit-tag.outputs.tag }}
          echo "::notice:: Commit Tagged."
