name: Scan Docker Image

on:
  workflow_call:
    inputs:
      namespace:
        description: "docker namespace"
        required: true
        type: string
      image:
        description: "docker image (name / file)"
        required: true
        type: string
      artifact:
        description: "artifact name"
        required: false
        type: string
      severity:
        description: "Image Scan Severities"
        type: string
        required: false
        default: "critical, high"
      scanners:
        description: "Image Scan Scanners"
        type: string
        required: false
        default: "quickview,cves,recommendations"
      ignore-base:
        description: "Ignore base image vulnerabilities"
        required: false
        type: boolean
        default: true
    secrets:
      docker_token:
        description: "Docker Token"
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: "artifact"

    steps:
      - name: Download Docker Image From Artifacts
        uses: actions/download-artifact@v4
        if: ${{ inputs.artifact }}
        with:
          name: ${{ inputs.artifact }}
          path: ${{ env.ARTIFACT_PATH }}

      - name: Setup Docker Scan
        id: scan-setup
        run: |
          if [ -n "${{ inputs.artifact }}" ]; then
            image="archive://${{ env.ARTIFACT_PATH }}/${{ inputs.image }}.tar"
          else
            image="${{ inputs.image }}"
          fi 
          echo "::notice:: > use (image): $image"
          echo "image=$image" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.namespace }}
          password: ${{ secrets.docker_token }}

      - name: Scan Docker Image
        uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations
          image: ${{ steps.scan-setup.outputs.image }}
          only-severities: ${{ inputs.severity }}
          ignore-base: ${{ inputs.ignore-base }}
