name: Scan Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "docker image (name / artifact.file)"
        required: true
        type: string    
      context:
        description: "docker build context (path)"
        required: false
        type: string
        default: .    
      artifact_name:
        description: "artifact name"
        required: false
        type: string       
      severity:
        description: "Image Scan Severities"
        type: string
        required: false
        default: "CRITICAL,HIGH"
      scanners:
        description: "Image Scan Scanners"
        type: string
        required: false
        default: "vuln,secret"        

jobs:        
  scan:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: "./artifacts"
      TRIVY_DB_VERSION: 2
      TRIVY_JAVA_DB_VERSION: 1
      TRIVY_CACHE_PATH: .cache/trivy
    steps: 
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Prepare/Setup Trivy
        id: scan-setup
        run: |
          echo "::notice:: Prepare/Setup Trivy..."
          TRIVY_IGNORE_FILE="${{ inputs.context }}/.trivyignore"
          if [ -f "$TRIVY_IGNORE_FILE" ]; then
            echo "::notice:: > use (trivyignores): $TRIVY_IGNORE_FILE"
          else
            echo "::notice:: > create empty $TRIVY_IGNORE_FILE"
            touch "$TRIVY_IGNORE_FILE"
          fi
          echo "trivyignores=${TRIVY_IGNORE_FILE}" >> $GITHUB_OUTPUT

          if [ -n "${{ inputs.artifact_name }}" ]; then
            INPUT="${{ env.ARTIFACT_PATH }}/${{ inputs.image }}.tar"
          else
            INPUT="${{ inputs.image }}"
          fi 
          echo "input=$INPUT" >> $GITHUB_OUTPUT          
          echo "::notice:: > use (input): $INPUT"
          
          echo "::notice:: > setup successfully"

      - name: Set Cache DBs Key
        id: cache-key
        run: |
          DATE=$(date +'%Y-%m-%d')
          KEY="cache-trivy-$DATE"
          echo "key=$KEY" >> $GITHUB_OUTPUT          

      - name: Load Cache DBs
        id: cache-trivy
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/${{ env.TRIVY_CACHE_PATH }}
          key: ${{ steps.cache-key.outputs.key }}          

      - name: Download and extract the vulnerability DB
        if: steps.cache-trivy.outputs.cache-hit != 'true'
        run: |
          mkdir -p $GITHUB_WORKSPACE/${{ env.TRIVY_CACHE_PATH }}/db
          oras pull ghcr.io/aquasecurity/trivy-db:${{ env.TRIVY_DB_VERSION }}
          tar -xzf db.tar.gz -C $GITHUB_WORKSPACE/.cache/trivy/db
          rm db.tar.gz          

      - name: Download and extract the Java DB
        if: steps.cache-trivy.outputs.cache-hit != 'true'
        run: |
          mkdir -p $GITHUB_WORKSPACE/${{ env.TRIVY_CACHE_PATH }}/java-db
          oras pull ghcr.io/aquasecurity/trivy-java-db:${{ env.TRIVY_JAVA_DB_VERSION }}
          tar -xzf javadb.tar.gz -C $GITHUB_WORKSPACE/.cache/trivy/java-db
          rm javadb.tar.gz   
          
      - name: Save DBs to cache
        if: steps.cache-trivy.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/${{ env.TRIVY_CACHE_PATH }}
          key: ${{ steps.cache-key.outputs.key }}

      - name: Download the Docker Image From Artifacts
        if: ${{ inputs.artifact_name }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ env.ARTIFACT_PATH }}
     
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          input: ${{ steps.scan-setup.outputs.input }}
          trivyignores: ${{ steps.scan-setup.outputs.trivyignores }}
          severity: ${{ inputs.severity }}
          scanners: ${{ inputs.scanners }}
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true
