name: Scan Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "docker image (name / artifact.file)"
        required: true
        type: string    
      context:
        description: "docker build context (path)"
        required: false
        type: string
        default: .    
      artifact_name:
        description: "artifact name"
        required: false
        type: string       
      severity:
        description: "Image Scan Severities"
        type: string
        required: false
        default: "CRITICAL,HIGH"
      scanners:
        description: "Image Scan Scanners"
        type: string
        required: false
        default: "vuln,secret"        

jobs:        
  scan:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: "./artifacts"
      TRIVY_VERSION: v0.56.1
    steps: 
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Prepare/Setup Trivy
        id: scan-setup
        run: |
          echo "::notice:: Prepare/Setup Trivy..."
          TRIVY_IGNORE_FILE="${{ inputs.context }}/.trivyignore"
          if [ -f "$TRIVY_IGNORE_FILE" ]; then
            echo "::notice:: > use (trivyignores): $TRIVY_IGNORE_FILE"
          else
            echo "::notice:: > create empty $TRIVY_IGNORE_FILE"
            touch "$TRIVY_IGNORE_FILE"
          fi
          echo "trivyignores=${TRIVY_IGNORE_FILE}" >> $GITHUB_OUTPUT

          if [ -n "${{ inputs.artifact_name }}" ]; then
            INPUT="${{ env.ARTIFACT_PATH }}/${{ inputs.image }}.tar"
          else
            INPUT="${{ inputs.image }}"
          fi 
          echo "input=$INPUT" >> $GITHUB_OUTPUT          
          echo "::notice:: > use (input): $INPUT"
          
          echo "::notice:: > setup successfully"

      - name: Download the Docker Image From Artifacts
        if: ${{ inputs.artifact_name }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ env.ARTIFACT_PATH }}      

      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: ${{ env.TRIVY_VERSION }}
     
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          input: ${{ steps.scan-setup.outputs.input }}
          trivyignores: ${{ steps.scan-setup.outputs.trivyignores }}
          severity: ${{ inputs.severity }}
          scanners: ${{ inputs.scanners }}
