name: Scan Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: "image name"
        type: string
        required: true
      artifact:
        description: "artifact name"
        type: string
        required: false
      scanner:
        description: "scanner to be used"
        type: string
        required: true
      config:
        description: "scanner config file"
        type: string
        required: false
    secrets:
      DOCKER_USERNAME:
        required: false
      DOCKER_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: "Load Docker Image From Artifact"
        id: load-image
        if: ${{ inputs.artifact }}
        uses: draftm0de/kernel.deployment/.github/actions/image-load@main
        with:
          image: ${{ inputs.image }}
          artifact: ${{ inputs.artifact }}

      - name: "Prepare Scan Arguments"
        id: arguments
        run: |
          echo "::notice:: Preparing Scan Arguments..."
          
          # ---------------------------------------------
          # set image name
          # ---------------------------------------------
          if [ -n "${{ steps.load-image.outputs.image }}" ]; then
            image="${{ steps.load-image.outputs.image }}"
          else
            image="${{ inputs.image }}"
          fi
          
          # ---------------------------------------------
          # verify config file
          # ---------------------------------------------
          if [ -n "${{ inputs.config }}" ]; then
            config="${{ inputs.config }}"
          else
            config=".${{ inputs.scanner }}.config"
          fi          
          if [ ! -f "${config}" ]; then
            echo "::error:: config file ${config} not found"
            exit 1
          fi
                    
          echo "::notice:: Scan arguments prepared."
          echo "image=$image" >> $GITHUB_OUTPUT
          echo "config=$config" >> $GITHUB_OUTPUT

      - name: "Login to Docker Hub"
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "Scan Image With Docker Scout"
        if: ${{ inputs.scanner == 'scout' }}
        uses: draftm0de/kernel.deployment/.github/actions/image-scan-scout@main
        with:
          image: ${{ steps.arguments.outputs.image }}
          config: ${{ steps.arguments.outputs.config }}

      - name: "Scan Image With Trivy"
        if: ${{ inputs.scanner == 'trivy' }}
        uses: draftm0de/kernel.deployment/.github/actions/image-scan-trivy@main
        with:
          image: ${{ steps.arguments.outputs.image }}
          config: ${{ steps.arguments.outputs.config }}