name: Protect Duplicate SHA

on:
  workflow_call:
    inputs:
      image:
        description: "docker image (name / artifact.file)"
        required: true
        type: string    
      artifact_name:
        description: "artifact name"
        required: false
        type: string  
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:        
  scan:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: "./artifacts"
    steps: 
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          repository: draftm0de/kernel.deployment

      - name: Download the Docker Image From Artifacts
        if: ${{ inputs.artifact_name }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ env.ARTIFACT_PATH }}      

      - name: Load Docker Image from Artifact
        if: ${{ inputs.artifact_name }}
        id: load-image
        run: |
          echo "::notice:: Load Docker Image..."
          
          INPUT="${{ env.ARTIFACT_PATH }}/${{ inputs.image }}.tar"
          echo "::notice:: > load from: ${INPUT}"
          
          IMAGE=$(docker load --input ${INPUT} | grep 'Loaded image' | awk '{print $3}')
          echo "::notice:: > image: $IMAGE"
          echo "image=${IMAGE}" >> $GITHUB_ENV

          echo "::notice:: > load successfully"

      - name: Get Local Image SHA
        run: |
          echo "::notice:: Get SHA..."
          
          SHA=$(./docker.sh image sha ${{ env.image }})
          echo "::notice:: > SHA for ${{ env.image }}: $SHA"
          
          echo "::notice:: > load successfully"
