name: Split and Iterate

on:
  workflow_call:
    inputs:
      tags:
        description: "Comma-separated list of items to process"
        required: true
        type: string

jobs:
  preprocess-and-iterate:
    runs-on: ubuntu-latest

    outputs:
      json_array: ${{ steps.prepare_array.outputs.json_array }}

    steps:
      # Step 1: Convert Comma-Separated String to JSON Array
      - name: Prepare JSON Array from Input
        id: prepare_array
        run: |
          items="${{ inputs.tags }}"
          if [[ -z "$items" ]]; then
            echo "Error: Input string is empty" >&2
            exit 1
          fi
          json_array=$(echo "[\"${items//,/\",\"}\"]")
          echo "json_array=$json_array"
          echo "json_array=$json_array" >> $GITHUB_OUTPUT

  process-each-item:
    needs: preprocess-and-iterate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ${{ fromJson(needs.preprocess-and-iterate.outputs.json_array) }}
    steps:
      - name: Process Each Item
        run: |
          echo "Processing item: ${{ matrix.item }}"
