name: Tag Commit Version

on:
  workflow_call:
    inputs:
      image:
        description: "Docker image without tag"
        type: string
        required: true
      digest:
        description: "Docker image digest"
        type: string
        required: true
      source:
        description: "Source branch"
        type: string
        required: false
      target:
        description: "Branch to be merged into"
        type: string
        required: false
    secrets:
      DOCKER_TOKEN:
        required: false

jobs:
  tag-commit:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-commit-tag.outputs.tag }}
    steps:
      - name: "Check Out Repository"
        uses: actions/checkout@v4

      - name: "Preparing Arguments"
        run: |
          echo "::group::Preparing Arguments"
          
          image="${{ inputs.image }}"
          repository="${image%%/*}"
          echo "> repository:$repository"          
          image="${image#*/}"
          echo "> image: $image"
          
          echo "::endgroup::"          
          echo "REPOSITORY=$repository" >> $GITHUB_ENV
          echo "IMAGE=$image" >> $GITHUB_ENV          

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ env.REPOSITORY }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "Build Commit Tag"
        id: get-commit-tag
        uses: draftm0de/kernel.deployment/.github/actions/build-commit-tag@main
        with:
          source: ${{ inputs.source || github.ref_name }}
          target: ${{ inputs.target || github.event.pull_request.base.ref }}
          image: ${{ inputs.image }}
          digest: ${{ inputs.digest }}

      - name: "Apply Commit Tag"
        if: ${{ steps.get-commit-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::group::Tagging Commit"
          
          tag="${{ steps.get-commit-tag.outputs.tag }}"
          echo "> tag: $tag"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # git tag ${tag}
          echo "> commit tagged with: $tag"
          # git push origin ${tag}
          echo "> commit push to origin with: $tag"      
          
          echo "::endgroup::"
