name: Tag Image and Commit

on:
  workflow_call:
    inputs:
      tags:
        description: "Comma-separated list of tags to process"
        required: true
        type: string

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.prepare_array.outputs.json_array }}
    steps:
      - name: Convert Tags From Input
        id: prepare_array
        run: |
          items="${{ inputs.tags }}"
          if [[ -z "$items" ]]; then
            echo "Error: Input string is empty" >&2
            exit 1
          fi
          json_array=$(echo "[\"${items//,/\",\"}\"]")
          echo "tags=$json_array" >> $GITHUB_OUTPUT
          
      - name: Download Artifact
        run: |
          echo "**notice** download artifact"

      - name: Load Artifact
        run: |
          echo "**notice** load artifact"

  tag:
    needs: preprocessing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ${{ fromJson(needs.preprocessing.outputs.tags) }}
    steps:
      - name: Tag Docker Image
        run: |
          echo "**notice** Tag Docker Image with ${{ matrix.item }}"
      
      - name: Tag Commit
        run: |
          if git ls-remote --heads origin ${{ matrix.item }} | grep -q ${{ matrix.item }}; then
            echo "tag_is_branch=true" >> $GITHUB_ENV
          else
            echo "tag_is_branch=false" >> $GITHUB_ENV
            
      - name: Process Tag as Non-Existing Branch
        if: env.tag_is_branch == 'false'
        run: |
          echo "**notice** Tag Commit with ${{ matrix.item }}"
          echo "**notice** Tag Image with with ${{ matrix.item }}"

  push:
    needs: tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ${{ fromJson(needs.preprocessing.outputs.tags) }}
    steps:
      - name: Tag is Branch
        run: |
          if git ls-remote --heads origin ${{ matrix.item }} | grep -q ${{ matrix.item }}; then
            echo "tag_is_branch=true" >> $GITHUB_ENV
          else
            echo "tag_is_branch=false" >> $GITHUB_ENV
            
      - name: Process Tag as Existing Branch
        if: env.tag_is_branch == 'true'
        run: |
          echo "**notice** Branch exists for tag: ${{ matrix.item }}. Processing accordingly."

      - name: Process Tag as Non-Existing Branch
        if: env.tag_is_branch == 'false'
        run: |
          echo "**notice** Branch does not exists for tag: ${{ matrix.item }}. Processing accordingly."          
